
export const MAKES = [
  "Toyota",
  "Mahindra",
  "Volkswagen",
  "Skoda",
  "Hyundai",
  "Maruti",
  "Tata",
  "Honda",
  "Kia",
];
export const FUELS = ["Petrol", "Diesel", "CNG", "EV"];

// Model options are keyed by Make so the "Model" field can be a proper
// dropdown (as shown in the target screenshot) instead of free text.
export const MODELS_BY_MAKE = {
  Toyota: ["Innova", "Fortuner", "Glanza", "Camry"],
  Mahindra: ["XUV700", "Scorpio", "Thar", "Bolero"],
  Volkswagen: ["Virtus", "Taigun", "Tiguan"],
  Skoda: ["Slavia", "Kushaq", "Octavia"],
  Hyundai: ["Verna", "Creta", "i20", "Venue"],
  Maruti: ["Swift", "Baleno", "Dzire", "Brezza"],
  Tata: ["Nexon", "Punch", "Harrier", "Altroz"],
  Honda: ["City", "Amaze", "Elevate"],
  Kia: ["Seltos", "Sonet", "Carens"],
};

// Extra reference lists used only by the "Update Customer & Vehicle
// Details" panel (vehicle/insurance/other sections).
export const PROFILE_CATEGORIES = [
  "Individual",
  "Corporate",
  "Fleet",
  "Government",
];
export const STATES = [
  "Tamilnadu",
  "Maharashtra",
  "Karnataka",
  "Delhi",
  "Gujarat",
  "Telangana",
  "Kerala",
  "Uttar Pradesh",
];
export const CITIES = [
  "Chennai",
  "Mumbai",
  "Bangalore",
  "Delhi",
  "Ahmedabad",
  "Hyderabad",
  "Kochi",
  "Pune",
  "Lucknow",
];
export const INSURERS = [
  "ICICI Lombard",
  "Bajaj Allianz",
  "HDFC Ergo",
  "Tata AIG",
  "New India Assurance",
];
export const YES_NO = ["Yes", "No"];

export const initialCustomers = [
  {
    id: "c1",
    name: "Ananya Desai",
    mobile: "9988776655",
    pincode: "411001",
    address: "34 FC Road, Pune",
    regNo: "MH12KL2345",
    make: "Toyota",
    model: "Innova",
    fuel: "Diesel",
  },
  {
    id: "c2",
    name: "Rajesh Gupta",
    mobile: "8877665544",
    pincode: "226001",
    address: "12 Hazratganj, Lucknow",
    regNo: "UP32MN6789",
    make: "Mahindra",
    model: "XUV700",
    fuel: "Diesel",
  },
  {
    id: "c3",
    name: "Meera Nair",
    mobile: "7766554433",
    pincode: "682001",
    address: "9 MG Road, Kochi",
    regNo: "KL07OP1234",
    make: "Volkswagen",
    model: "Virtus",
    fuel: "Petrol",
  },
  {
    id: "c4",
    name: "Suresh Joshi",
    mobile: "6655443322",
    pincode: "380001",
    address: "67 CG Road, Ahmedabad",
    regNo: "GJ01QR5678",
    make: "Skoda",
    model: "Slavia",
    fuel: "Petrol",
  },
  {
    id: "c5",
    name: "Kavita Rao",
    mobile: "5544332211",
    pincode: "600001",
    address: "21 Anna Salai, Chennai",
    regNo: "TN09ST9012",
    make: "Hyundai",
    model: "Verna",
    fuel: "CNG",
  },
  {
    id: "c6",
    name: "Arjun Mehta",
    mobile: "9876543210",
    pincode: "110001",
    address: "45 Connaught Place, Delhi",
    regNo: "DL04CA2847",
    make: "Maruti",
    model: "Swift",
    fuel: "Petrol",
  },
  {
    id: "c7",
    name: "Priya Sharma",
    mobile: "8765432109",
    pincode: "400053",
    address: "12 Bandra West, Mumbai",
    regNo: "MH02EF5621",
    make: "Tata",
    model: "Nexon",
    fuel: "Diesel",
  },
  {
    id: "c8",
    name: "Rahul Verma",
    mobile: "7654321098",
    pincode: "560034",
    address: "8 Koramangala, Bangalore",
    regNo: "KA05MH7734",
    make: "Honda",
    model: "City",
    fuel: "Petrol",
  },
  {
    id: "c9",
    name: "Sneha Patel",
    mobile: "6543210987",
    pincode: "380015",
    address: "33 SG Highway, Ahmedabad",
    regNo: "GJ01KL4456",
    make: "Kia",
    model: "Seltos",
    fuel: "EV",
  },
  {
    id: "c10",
    name: "Deepak Iyer",
    mobile: "9988776655",
    pincode: "500032",
    address: "7 Jubilee Hills, Hyderabad",
    regNo: "TS09AB1298",
    make: "Toyota",
    model: "Fortuner",
    fuel: "Diesel",
  },
  {
    id: "c11",
    name: "Deepak Iyer",
    mobile: "9988776655",
    pincode: "500032",
    address: "7 Jubilee Hills, Hyderabad",
    regNo: "TS09AB1298",
    make: "Toyota",
    model: "Fortuner",
    fuel: "Diesel",
  },
];
