export const kpiStats = [
  {
    id: "service",
    title: "Service Reminders",
    count: 10,
    label: "Vehicles",
    tone: "blue",
  },
  {
    id: "booking",
    title: "Booking Reminders",
    count: 5,
    label: "Upcoming Bookings",
    tone: "emerald",
  },
  {
    id: "insurance",
    title: "Insurance Reminders",
    count: 4,
    label: "Policies Expiring",
    tone: "purple",
  },
  {
    id: "rsa",
    title: "RSA Reminders",
    count: 2,
    label: "Fleet Expiring",
    tone: "amber",
  },
];

export const initialServiceReminders = [
  {
    id: "sr-1",
    customer: "Ajay Kumar",
    phone: "+91 98765 43210",
    vehicle: "Toyota Hiace",
    regNo: "TN 87 XX 124",
    serviceType: "Periodic Service",
    dueDate: "18 May 2024",
    dueLeft: "2 Days",
    status: "Due Soon",
  },
  {
    id: "sr-2",
    customer: "Rajesh",
    phone: "+91 98765 43210",
    vehicle: "Hyundai Creta",
    regNo: "KA 01 CR 9876",
    serviceType: "Battery Service",
    dueDate: "20 May 2024",
    dueLeft: "4 Days",
    status: "Due Soon",
  },
  {
    id: "sr-3",
    customer: "Kavi",
    phone: "+91 98765 43210",
    vehicle: "Maruti Swift",
    regNo: "TN 09 BF 001",
    serviceType: "Periodic Service",
    dueDate: "25 May 2024",
    dueLeft: "9 Days",
    status: "Upcoming",
  },
  {
    id: "sr-4",
    customer: "Anand",
    phone: "+91 98765 43210",
    vehicle: "Honda City",
    regNo: "KA 05 AY 6458",
    serviceType: "Oil Change",
    dueDate: "28 May 2024",
    dueLeft: "15 Days",
    status: "Upcoming",
  },
  {
    id: "sr-5",
    customer: "Kishore",
    phone: "+91 98765 43210",
    vehicle: "Tata Nexon",
    regNo: "MH 12 LN 2200",
    serviceType: "General Service",
    dueDate: "30 May 2024",
    dueLeft: "14 Days",
    status: "Upcoming",
  },
  {
    id: "sr-6",
    customer: "Suresh P",
    phone: "+91 98765 11111",
    vehicle: "Mahindra Thar",
    regNo: "KA 51 M 9900",
    serviceType: "Brake Inspection",
    dueDate: "02 Jun 2024",
    dueLeft: "17 Days",
    status: "Upcoming",
  },
  {
    id: "sr-7",
    customer: "Priya M",
    phone: "+91 98765 22222",
    vehicle: "Kia Seltos",
    regNo: "DL 03 C 4455",
    serviceType: "AC Service",
    dueDate: "05 Jun 2024",
    dueLeft: "3 Days",
    status: "Due Soon",
  },
  {
    id: "sr-8",
    customer: "Venkatesh",
    phone: "+91 98765 33333",
    vehicle: "Toyota Innova",
    regNo: "KA 04 E 1234",
    serviceType: "Periodic Service",
    dueDate: "08 Jun 2024",
    dueLeft: "23 Days",
    status: "Upcoming",
  },
  {
    id: "sr-9",
    customer: "Dinesh K",
    phone: "+91 98765 44444",
    vehicle: "Hyundai Verna",
    regNo: "TN 22 B 7890",
    serviceType: "Wheel Alignment",
    dueDate: "10 Jun 2024",
    dueLeft: "25 Days",
    status: "Upcoming",
  },
  {
    id: "sr-10",
    customer: "Ramesh R",
    phone: "+91 98765 55555",
    vehicle: "Tata Harrier",
    regNo: "MH 02 DF 5678",
    serviceType: "Full Service",
    dueDate: "12 Jun 2024",
    dueLeft: "1 Days",
    status: "Due Soon",
  },
];

export const bookingReminders = [
  {
    id: "b1",
    customer: "Deep R",
    vehicle: "Honda Amaze",
    date: "18 May",
    status: "Confirmed",
    tone: "emerald",
  },
  {
    id: "b2",
    customer: "Aarush",
    vehicle: "Hyundai Creta",
    date: "19 May",
    status: "Confirmed",
    tone: "emerald",
  },
  {
    id: "b3",
    customer: "Sarah J",
    vehicle: "Maruti Swift",
    date: "20 May",
    status: "Pending",
    tone: "amber",
  },
  {
    id: "b4",
    customer: "Karan M",
    vehicle: "Kia Seltos",
    date: "22 May",
    status: "Confirmed",
    tone: "emerald",
  },
  {
    id: "b5",
    customer: "Pooja S",
    vehicle: "Toyota Glanza",
    date: "24 May",
    status: "Pending",
    tone: "amber",
  },
];

export const insuranceReminders = [
  {
    id: "i1",
    customer: "Raj Kumar",
    policy: "Bajaj Allianz",
    expiry: "20 May",
    status: "7 Days",
    tone: "purple",
  },
  {
    id: "i2",
    customer: "Sneha P",
    policy: "Reliance General",
    expiry: "21 May",
    status: "Expiring",
    tone: "rose",
  },
  {
    id: "i3",
    customer: "Ajay V",
    policy: "HDFC Ergo",
    expiry: "25 May",
    status: "Renewal Due",
    tone: "indigo",
  },
  {
    id: "i4",
    customer: "Vikram R",
    policy: "ICICI Lombard",
    expiry: "28 May",
    status: "14 Days",
    tone: "purple",
  },
  {
    id: "i5",
    customer: "Meena K",
    policy: "TATA AIG",
    expiry: "30 May",
    status: "Renewal Due",
    tone: "indigo",
  },
];

export const rsaReminders = [
  {
    id: "r1",
    customer: "Aarav V",
    vehicle: "Royal Enfield",
    expiry: "20 May",
    status: "3 Days",
    tone: "amber",
  },
  {
    id: "r2",
    customer: "Manav K",
    vehicle: "Mahindra",
    expiry: "21 May",
    status: "Expiring",
    tone: "rose",
  },
  {
    id: "r3",
    customer: "Ravi S",
    vehicle: "Tata Nexon",
    expiry: "25 May",
    status: "2 Days",
    tone: "amber",
  },
  {
    id: "r4",
    customer: "Sanjay N",
    vehicle: "TVS Apache",
    expiry: "27 May",
    status: "9 Days",
    tone: "emerald",
  },
  {
    id: "r5",
    customer: "Ganesh B",
    vehicle: "Hero Splendor",
    expiry: "29 May",
    status: "11 Days",
    tone: "emerald",
  },
];
