import {
  LayoutDashboard,
  Database,
  Wrench,
  Receipt,
  CalendarDays,
  BarChart3,
  Phone,
  Package,
  Users,
  ScrollText,
  ClipboardCheck,
  ListTree,
  Boxes,
  TrendingUp,
  ShoppingCart,
  UploadCloud,
  FileCheck,
  UserPlus,
  FileText,
  UserCheck,
  Settings2,
  ShieldCheck,
  MessageSquareWarning,
  Circle,
  Wallet,
  CalendarCheck,
  Plug,
  Cog,
  Megaphone,
  Bell,
} from "lucide-react";

const ICON_MAP = {
  dashboard: LayoutDashboard,
  master: Database,
  transaction: Wrench,
  service: Wrench,
  receipts: Receipt,
  attendance: CalendarCheck,
  integration: Plug,
  calendar: CalendarDays,
  report: BarChart3,
  call: Phone,
  parts: Cog,
  item: Package,
  user: Users,
  log: ScrollText,
  fitmaster: ClipboardCheck,
  menus: ListTree,
  stock: Boxes,
  sale: TrendingUp,
  purchase: ShoppingCart,
  marketing: Megaphone,
  reminder: Bell,
  bulk: UploadCloud,
  approvedestimates: FileCheck,
  leadmanagement: UserPlus,
  contractsale: FileText,
  customerapprove: UserCheck,
  masters: Database,
  users: Users,
  receipt: Receipt,
  reports: BarChart3,
  logs: ScrollText,
  menu: ListTree,
  items: Package,
  settings: Settings2,
  shield: ShieldCheck,
  complaint: MessageSquareWarning,
  finance: Wallet,
  catalogue: Package,
};
export function resolveIcon(iconName) {
  if (!iconName) return Circle;
  const key = String(iconName)
    .replace(/active$/i, "")
    .toLowerCase();
  return ICON_MAP[key] ?? Circle;
}
