export const JOBCARD_KPIS = [
  {
    key: "initiated",
    label: "Initiated",
    value: 431,
    icon: "wrench",
    active: true,
  },
  { key: "inprogress", label: "Inprogress", value: 1, icon: "truck" },
  { key: "delivered", label: "Delivered", value: 2, icon: "check-circle" },
  {
    key: "ready-for-delivery",
    label: "Ready For Delivery",
    value: 2,
    icon: "clipboard",
  },
  {
    key: "next-day-delivery",
    label: "Next Day Delivery",
    value: 16,
    icon: "calendar",
  },
  {
    key: "upcoming-delivery",
    label: "Upcoming Delivery",
    value: 85,
    icon: "credit-card",
  },
];

export const JOBCARD_STATUSES = [
  "Repair Work",
  "Delivery",
  "Delivered",
  "Completed",
  "Estimate",
  "On Hold",
];

export const STATUS_BADGE = {
  "Repair Work": "bg-blue-50 text-blue-700",
  Delivery: "bg-violet-50 text-violet-700",
  Delivered: "bg-emerald-50 text-emerald-700",
  Completed: "bg-emerald-50 text-emerald-700",
  Estimate: "bg-amber-50 text-amber-700",
  "On Hold": "bg-red-50 text-red-700",
};

export const DELIVERY_STATE_BADGE = {
  Billing: "bg-blue-50 text-blue-700",
  Parts: "bg-amber-50 text-amber-700",
  "Gate Pass": "bg-violet-50 text-violet-700",
  Feedback: "bg-emerald-50 text-emerald-700",
  Completed: "bg-emerald-50 text-emerald-700",
  "On Hold": "bg-red-50 text-red-700",
};

export const MECHANICS = [
  { name: "Manoj", role: "Senior Mechanic", rating: 4.8 },
  { name: "Karthik", role: "Technician", rating: 4.6 },
  { name: "Vikram", role: "Body Shop Head", rating: 4.9 },
  { name: "Anand", role: "Technician", rating: 4.7 },
  { name: "Deepak", role: "Technician", rating: 4.5 },
  { name: "Ajay Kumar", role: "Senior Mechanic", rating: 4.8 },
];

export const initialJobCards = [
  {
    id: "JC-CARD-2345",
    status: "Repair Work",
    subtitle: "Premium Hatchback",
    customer: {
      name: "Arun Kumar",
      regNo: "TN 09 CK 1234",
      model: "Hyundai Creta SX (O)",
    },
    estimate: { id: "EST: 2405-0193", amount: 12827.4, approved: true },
    discount: { amount: 1542, percent: 12.75 },
    insurance: { company: "ICICI Lombard", claim: "Claimable", amount: 7450 },
    assignedTo: { name: "Manoj", role: "Senior Mechanic", rating: 4.8 },
    progress: 89,
    progressColor: "blue",
    delivery: {
      state: "Billing",
      note: "Payment Pending",
      timer: "1d 30m to go",
      timerTone: "ok",
    },
    dates: { assigned: "16 May, 10:30 AM", eth: "20 May, 06:00 PM" },
  },
  {
    id: "JC-CARD-2344",
    status: "Repair Work",
    subtitle: "Premium Sedan",
    customer: {
      name: "Naveen Kumar",
      regNo: "TN 08 BD 2211",
      model: "Honda City V CVT",
    },
    estimate: { id: "EST: 2405-0179", amount: 8920, approved: true },
    discount: { amount: 980, percent: 11 },
    insurance: { company: "HDFC Ergo", claim: "Claimable", amount: 5300 },
    assignedTo: { name: "Karthik", role: "Technician", rating: 4.6 },
    progress: 40,
    progressColor: "amber",
    delivery: {
      state: "Parts",
      note: "Waiting for Parts",
      timer: "Exceeded 1d 30m",
      timerTone: "bad",
    },
    dates: { assigned: "16 May, 10:30 AM", eth: "20 May, 06:00 PM" },
  },
  {
    id: "JC-CARD-2343",
    status: "Delivery",
    subtitle: "SUV",
    customer: {
      name: "Priya Nair",
      regNo: "KA 03 ME 4321",
      model: "Maruti Grand Vitara",
    },
    estimate: { id: "EST: 2405-0175", amount: 24350, approved: true },
    discount: { amount: 2435, percent: 10 },
    insurance: { company: "Bajaj Allianz", claim: "Claimable", amount: 18500 },
    assignedTo: { name: "Vikram", role: "Body Shop Head", rating: 4.9 },
    progress: 95,
    progressColor: "violet",
    delivery: {
      state: "Gate Pass",
      note: "Pre Delivery Done",
      timer: "30m to go",
      timerTone: "ok",
    },
    dates: { assigned: "16 May, 10:30 AM", eth: "20 May, 06:00 PM" },
  },
  {
    id: "JC-CARD-2342",
    status: "Delivered",
    subtitle: "MPV",
    customer: {
      name: "Suresh Babu",
      regNo: "TN 11 X 9876",
      model: "Toyota Innova Crysta",
    },
    estimate: { id: "EST: 2405-0168", amount: 4322, approved: true },
    discount: { amount: 520.2, percent: 12.03 },
    insurance: { company: "No Claim", claim: "Direct Billing" },
    assignedTo: { name: "Anand", role: "Technician", rating: 4.7 },
    progress: 100,
    progressColor: "emerald",
    delivery: {
      state: "Feedback",
      note: "Rating Pending",
      timer: "On time",
      timerTone: "ok",
    },
    dates: { assigned: "16 May, 10:30 AM", eth: "20 May, 06:00 PM" },
  },
  {
    id: "JC-CARD-2341",
    status: "Completed",
    subtitle: "Hatchback",
    customer: {
      name: "Ramesh R",
      regNo: "TN 05 AQ 7788",
      model: "Kia Seltos HTK",
    },
    estimate: { id: "EST: 2405-0152", amount: 7853, approved: true },
    discount: { amount: 785.3, percent: 10 },
    insurance: { company: "No Claim", claim: "Direct Billing" },
    assignedTo: { name: "Deepak", role: "Technician", rating: 4.5 },
    progress: 100,
    progressColor: "emerald",
    delivery: {
      state: "Completed",
      note: "Feedback Done",
      timer: "Delivered",
      timerTone: "ok",
    },
    dates: { assigned: "16 May, 10:30 AM", eth: "20 May, 06:00 PM" },
  },
  {
    id: "JC-CARD-2340",
    status: "Estimate",
    subtitle: "SUV",
    customer: {
      name: "Manoj Patel",
      regNo: "TN 07 CD 8855",
      model: "Mahindra Thar",
    },
    estimate: { id: "EST: 2405-0130", amount: 18350, approved: true },
    discount: { amount: 1835, percent: 10 },
    insurance: { company: "ICICI Lombard", claim: "Claimable", amount: 14200 },
    assignedTo: { name: "Manoj", role: "Senior Mechanic", rating: 4.8 },
    progress: 25,
    progressColor: "red",
    delivery: {
      state: "On Hold",
      note: "Re-Estimate Required",
      timer: "Exceeded 60m",
      timerTone: "bad",
    },
    dates: { assigned: "16 May, 10:30 AM", eth: "20 May, 06:00 PM" },
  },
];

/** Complete jobcard record used by the wizard - matches screenshots 3-11. */
export const initialJobCardDetail = {
  id: "JC-2024-08-01-0001",
  status: "Open",
  customer: {
    name: "Ajay Kumar",
    mobile: "9176177546",
    pincode: "600072",
    address: "34 FC Road, Pune",
    regNo: "MH12KL2345",
    make: "Toyota",
    model: "Innova",
    fuel: "Diesel",
  },
  insuranceEnabled: true,
  insurance: {
    location: "",
    insurer: "",
    areaName: "",
    pincode: "",
    city: "",
    claimNo: "",
    gstin: "",
    policyNo: "",
    expiryDate: "",
    surveyorName: "",
    surveyorMobile: "",
    surveyorEmail: "",
    estimatedCost: "15000",
    surveyorIntimatedDate: "",
    surveyorProposedDate: "",
    surveyorVisitedDate: "",
    surveyorApprovedDate: "",
    coverage: "Comprehensive",
    settlementType: "Cashless",
  },
  inventory: {
    fuelLevel: 0.75, // 3/4
    odometer: "23859",
    checked: ["Vehicle Charger EV", "Floor Mat", "Steering Wrap Cover"],
    total: 6,
  },
  inspection: {
    filter: "All",
    // status: green | orange | red
    items: {
      "Engine Oil Level": "green",
      "Coolant Level": "orange",
      "Brake Fluid Level": "red",
      "Power Steering Fluid": "green",
      "Battery Condition": "green",
      "Air Filter": "orange",
      "Fuel Filter": "red",
      "Spark Plugs": "orange",
      "Brake Pads (Front)": "orange",
      "Brake Pads (Rear)": "red",
      "Tyre Condition (FL)": "green",
      "Tyre Condition (FR)": "green",
      "Tyre Condition (RL)": "orange",
      "Tyre Condition (RR)": "red",
      "Wiper Blades": "green",
      "AC Cooling": "green",
    },
    notes: "",
  },
  tyres: {
    battery: { voltage: "12.48", status: "green", notes: "" },
    tread: { FL: 6.2, FR: 6.0, RL: 5.8, RR: 5.6 },
  },
  complaints: [
    {
      id: "c1",
      complaint: "Brake Problem",
      advice: "Brakepads worn, Fluid is low",
      attended: true,
    },
    {
      id: "c2",
      complaint: "Brake Problem",
      advice: "Brakepads worn, Fluid is low",
      attended: true,
    },
  ],
  parts: [
    {
      id: "row-p1",
      partNo: "54636",
      name: "AIR CLEANER ELEMENT",
      hsn: "54636",
      qty: 1,
      rate: 2288,
      sgst: 0,
      cgst: 0,
      igst: 18,
      disc: 10,
      approval: "Approved",
    },
    {
      id: "row-p2",
      partNo: "8421",
      name: "OIL FILTER",
      hsn: "8421",
      qty: 1,
      rate: 2288,
      sgst: 9,
      cgst: 9,
      igst: 0,
      disc: 5,
      approval: "Approved",
    },
    {
      id: "row-p3",
      partNo: "8511",
      name: "SPARK PLUG",
      hsn: "8511",
      qty: 4,
      rate: 2288,
      sgst: 9,
      cgst: 9,
      igst: 0,
      disc: 0,
      approval: "Pending",
    },
  ],
  labour: [
    {
      id: "row-l1",
      code: "LAB-100",
      description: "General Service",
      type: "Paid Service",
      hrs: 1.5,
      rate: 600,
      sgst: 0,
      cgst: 0,
      igst: 18,
      disc: 0,
      approval: "Approved",
    },
    {
      id: "row-l2",
      code: "LAB-200",
      description: "Wheel Alignment",
      type: "Paid Service",
      hrs: 1,
      rate: 800,
      sgst: 9,
      cgst: 9,
      igst: 0,
      disc: 10,
      approval: "Approved",
    },
  ],
  osl: [
    {
      id: "row-o1",
      code: "OSL-100",
      description: "Consumables & Shop Supplies",
      type: "Outsourced",
      hrs: 1,
      rate: 6863.16,
      sgst: 9,
      cgst: 9,
      igst: 0,
      disc: 0,
      approval: "Approved",
    },
  ],
  includeGST: true,
  coupon: "GHSJ5783",
  payment: {
    mode: "UPI",
    date: "2024-05-16",
    received: "9284.65",
    balance: "0.00",
    upi: "arun@ybl",
    remarks: "Payment received via GooglePay",
  },
  vehicleImages: [
    "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=200",
    "https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=200",
    "https://images.unsplash.com/photo-1553440569-bcc63803a83d?w=200",
    "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=200",
  ],
  technicians: [
    {
      id: "t1",
      labour: "Labour",
      stdHrs: "",
      mechanic: "Ajay Kumar (Senior Mechanic)",
      workAllocated: "100",
      startAt: "Apr 12, 10:00AM",
      endAt: "Apr 12, 10:00AM",
      mechanicHrs: "2Hrs",
      reason: "",
      status: "Work in Progress",
    },
    {
      id: "t2",
      labour: "Labour",
      stdHrs: "",
      mechanic: "Ajay Kumar (Senior Mechanic)",
      workAllocated: "100",
      startAt: "",
      endAt: "",
      mechanicHrs: "2Hrs",
      reason: "",
      status: "Work in Progress",
    },
  ],
  completedWorks: [
    {
      id: "w1",
      description: "Brake Pads Replacement (Front)",
      kind: "Labour",
      estTime: "1.0 Hr",
      technician: "Karthik",
      techRole: "Technician",
      videoUrl: "https://example.com/v1",
      videoLen: "00:25",
    },
    {
      id: "w2",
      description: "Engine Oil Change",
      kind: "Labour",
      estTime: "1.0 Hr",
      technician: "Manoj",
      techRole: "Senior Mechanic",
      videoUrl: null,
    },
    {
      id: "w3",
      description: "Air Filter Replacement",
      kind: "Part",
      partNo: "54636",
      estTime: "0.3 Hr",
      technician: "Vikram",
      techRole: "Technician",
      videoUrl: "https://example.com/v3",
      videoLen: "00:25",
    },
  ],
  returnOldParts: [{ id: "r1", name: "Rear Left Light" }],
  nextService: {
    currentOdo: "72,350",
    avgKm: "40",
    nextInKm: "10,000",
    nextOnDate: "2024-08-16",
    dueLabel: "82,350 KM / 16 Aug 2024",
  },
  maintenance: [
    {
      item: "Inspection Service",
      recommended: "5,000",
      dueIn: "2,650",
      dueDate: "25 Jun 2024",
      status: "Due Soon",
    },
    {
      item: "Tyre Rotation",
      recommended: "10,000",
      dueIn: "2,650",
      dueDate: "16 Aug 2024",
      status: "Due Soon",
    },
    {
      item: "Tyre Replacement",
      recommended: "40,000",
      dueIn: "32,650",
      dueDate: "-",
      status: "Upcoming",
    },
    {
      item: "Battery Replacement",
      recommended: "30,000",
      dueIn: "22,650",
      dueDate: "-",
      status: "Upcoming",
    },
    {
      item: "Suspension Check",
      recommended: "20,000",
      dueIn: "12,650",
      dueDate: "-",
      status: "Upcoming",
    },
  ],
  feedback: {
    ratings: {
      "Greet & Welcome": 4,
      "Lounge Experience": 3,
      "Service Advisor Hospitality": 4,
      "Quality of Service": 5,
      "Timely Delivery": 3,
      "Overall Satisfaction": 4,
    },
    comments: "",
  },
  estimateApproval: {
    status: "Awaiting Approval",
    timeline: [
      {
        key: "created",
        label: "Estimate Created",
        at: "16 May 2024, 10:30 AM",
        done: true,
      },
      {
        key: "sent",
        label: "Sent to Customer",
        at: "16 May 2024, 10:35 AM",
        done: false,
        active: true,
      },
      { key: "approved", label: "Customer Approved", at: "-", done: false },
      { key: "jobcard", label: "Job Card Created", at: "-", done: false },
    ],
    mode: "customer",
  },
};

// Same catalog + categories the Estimate module uses; re-exported here so
// jobcard components don't reach across module boundaries at import time.
export {
  CATALOG,
  CATEGORIES,
  INSURERS,
  MAKES,
  FUELS,
} from "@/pages/service/mockEstimates";
